### ISSUE TITLE
Result of evaluate.py show more than 70% error 

### ISSUE THREAD

**Issue by harrainy** [datvuthanh/Efficient-Deep-Learning-for-Stereo-Matching-Keras#1]
The disparity map from evaluate.py shows more than 70% error comparing to GT results.

**Comment by datvuthanh** [comment]
You can remove scale_factor variable.
```
pred = tf.argmax(cost_volume, axis=2)
# Convert tensor to array
pred = pred.numpy() 

#disp_targets = disp_targets[0:pred.shape[0], 0:pred.shape[1]] 

valid_gt_pixels = (disp_targets != 0).astype('float')

masked_prediction_valid = pred * valid_gt_pixels

num_valid_gt_pixels = valid_gt_pixels.sum()

# NOTE: Use 3-pixel error metric for now.
num_error_pixels = (np.abs(masked_prediction_valid - disp_targets) > 3).sum()

error += num_error_pixels / num_valid_gt_pixels
```

**Comment by harrainy** [comment]
This does not solve the problem. In the code previously, both pred and disp_targets are multiplied by the scale_factor. Removing scale_factor from both of them does not help. I also tried to compare the output in disp_images/step_40000 with ground truth, which also gives about 70% error.

**Comment by datvuthanh** [comment]
Send me your cost volume (.npy) and disparity map image (.png) to datvthe140592@fpt.edu.vn!

**Comment by datvuthanh** [comment]
The problem is scale_factor, this is my fault. When you read a gray image, when need to transform value from (0,255) to (0,disp_range). You can add a new variables ```scale = 1 / 255 * float(disp_range)``` instead of scale_factor (remember that you need convert image to np.int16) or you can use this code below!

```
pred = tf.argmax(cost_volume, axis=2)
# Convert tensor to array
pred = pred.numpy() 
disp_range = 201

gt = np.float32(cv2.imread('url_here', cv2.IMREAD_GRAYSCALE)) # Convert to grayscale
gt = np.int16(gt / 255.0 * float(disp_range)) # 

pred = np.int16(np.float32(pred) / 255.0 * float(disp_range))
err = np.count_nonzero(np.abs(pred - gt) > 3)

err_total  = float(err) / (gt.shape[0] * gt.shape[1])
```

**Comment by harrainy** [comment]
Thank you. But it is still not working as expected. The error is still around 70%. Could you update the evaluate.py file with a working one?

**Comment by datvuthanh** [comment]
Please send me your cost volume (.npy) and disparity image (grouth truth) to my email: stephenvu98@gmail.com, I will check for you.

**Comment by datvuthanh** [comment]
Hi @harrainy, I've updated my latest commit. Check it again!

**Comment by harrainy18** [comment]
Thank you. It works now!

**Comment by harrainy** [comment]
Thank you. It works now!
