### ISSUE TITLE
Pretrained model

### ISSUE THREAD

**Issue by rodrigoGA** [datvuthanh/Efficient-Deep-Learning-for-Stereo-Matching-Keras#2]
Thanks for sharing the work,
Do you have a pre-trained model?
Is the model exportable to tensorflow lite?

**Comment by datvuthanh** [comment]
Hi rodrigoGA, you may find my pretrained model in checkpoint folder. Your question about exporting to TensorFlow lite, I don't have any experience with it. I am sorry about that!
