### ISSUE TITLE
feature request: Inference code in a single model

### ISSUE THREAD

**Issue by rodrigoGA** [datvuthanh/Efficient-Deep-Learning-for-Stereo-Matching-Keras#3]
I don't know if it is appropriate to make a issue for this.

But to make an inference, a process is performed with a purely convolutional model and then other operations are performed outside the model.  https://github.com/datvuthanh/Stereo-Matching/blob/33f9f391a298e0cd43822b2e29a9dbf5a4fc318b/inference.py#L122

But I wanted to ask you about the possibility of the inference code can be turned into a single TF model by using tf.function.

In this way the model would be exportable to tensorflow lite, and used by edge devices.

**Comment by datvuthanh** [comment]
Hi rodrigoGA,

Yes, you can modify this code to use tf.function. No problem!
